export enum ErrorCode {
    // Validation
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    INVALID_INPUT = 'INVALID_INPUT',
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
    INVALID_FORMAT = 'INVALID_FORMAT',

    // Authentication/Authorization
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

    // Resource
    NOT_FOUND = 'NOT_FOUND',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

    // Server
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    VALIDATION_PROCESSING_ERROR = 'VALIDATION_PROCESSING_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

    // Business Logic
    CONFLICT = 'CONFLICT',
    DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
    BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',

    // Request Limit
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
}
